### ISSUE TITLE
Would you prefer SwiftUI or UIKit?

### ISSUE THREAD

**Issue by mrtrinh5293** [raywenderlich/ios-interview#6]
Hello Raywenderlich,
Firstly thank you for your supports and very interesting IOS interview prep. I really like the useful review live.
As the title already mentioned, would you prefer the practical project develops with UIKit or SwiftUI?

**Comment by marinbenc** [comment]
@mrtrinh5293 feel free to use SwiftUI or UIKit, whichever you prefer.
