### ISSUE TITLE
JSON data is no longer available

### ISSUE THREAD

**Issue by yeshusingh** [raywenderlich/ios-interview#8]
Hello..

Just observed today that the JSON data link in the Practical iOS project no longer. 
It shows below error 
"{"message":"API Requests Quota is Exhausted. Purchase more requests at https://jsonbin.io/pricing.","success":false}" 

I started working on the project maybe after a week or so, hence observed it today but it's possible the link is working since few days.
Will this be made available again or I and/or other folks have reached their limit on the usage on the links.

Thanks,
Yeshu

**Comment by rramirez-dev** [comment]
I'm having the same issue

**Comment by leamars** [comment]
Hey all! We're working on fixing it, and we'll update the link both here and in the article once it's been done (: 

Thanks for flagging!

**Comment by leamars** [comment]
Hey all! We've update the Example project with the new JSON files hosted directly on this repository. Please see the updated readme for the new instructions, https://github.com/raywenderlich/ios-interview/tree/master/Practical%20Example

@rramirez-dev 
@yeshusingh
